name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Enable pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install -e .
          python -m pip install ruff pytest pip-licenses
      - name: Lint (soft on first run)
        run: |
          ruff format --check .
          ruff check --output-format=github --exit-zero .
      - name: Tests
        run: pytest -q
      - name: Generate third-party notices (artifact)
        run: |
          pip-licenses --format=markdown --with-urls --with-license-file --output-file THIRD_PARTY_NOTICES.md || true
      - uses: actions/upload-artifact@v4
        with:
          name: third-party-notices
          path: THIRD_PARTY_NOTICES.md
